baseURL: "https://althaser.me/"
languageCode: en-us
build:
  writeStats: true
# https://www.markdownguide.org/tools/hugo/
# https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
  goldmark:
    renderer:
      unsafe: true
title: "althaser's website"
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu
params:
  author: Pedro Beja
  description: althaser's website
  copyright: >-
    Powered by [hugo](https://gohugo.io/)
  analytics:
    googleTagId: G-GL1PZQ4MJH
  assets:
    fontAwesome:
      url: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css
      integrity: sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==
    academiconsUrl: https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css
    googleFontsUrl: https://fonts.googleapis.com/css?family=Didact+Gothic%7CRoboto:400%7CRoboto+Mono
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
    - item: links
      expand: true    # default - only the first `expand: true` will take effect
    # - item: skills
    #  panel_id: skill-panel
